// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CfgEquipment is the predicate function for cfgequipment builders.
type CfgEquipment func(*sql.Selector)
