// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"harvest/app/worker/internal/data/ent/cfgequipment"
	"harvest/app/worker/internal/data/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CfgEquipmentQuery is the builder for querying CfgEquipment entities.
type CfgEquipmentQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.CfgEquipment
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CfgEquipmentQuery builder.
func (ceq *CfgEquipmentQuery) Where(ps ...predicate.CfgEquipment) *CfgEquipmentQuery {
	ceq.predicates = append(ceq.predicates, ps...)
	return ceq
}

// Limit adds a limit step to the query.
func (ceq *CfgEquipmentQuery) Limit(limit int) *CfgEquipmentQuery {
	ceq.limit = &limit
	return ceq
}

// Offset adds an offset step to the query.
func (ceq *CfgEquipmentQuery) Offset(offset int) *CfgEquipmentQuery {
	ceq.offset = &offset
	return ceq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ceq *CfgEquipmentQuery) Unique(unique bool) *CfgEquipmentQuery {
	ceq.unique = &unique
	return ceq
}

// Order adds an order step to the query.
func (ceq *CfgEquipmentQuery) Order(o ...OrderFunc) *CfgEquipmentQuery {
	ceq.order = append(ceq.order, o...)
	return ceq
}

// First returns the first CfgEquipment entity from the query.
// Returns a *NotFoundError when no CfgEquipment was found.
func (ceq *CfgEquipmentQuery) First(ctx context.Context) (*CfgEquipment, error) {
	nodes, err := ceq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cfgequipment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ceq *CfgEquipmentQuery) FirstX(ctx context.Context) *CfgEquipment {
	node, err := ceq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CfgEquipment ID from the query.
// Returns a *NotFoundError when no CfgEquipment ID was found.
func (ceq *CfgEquipmentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ceq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cfgequipment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ceq *CfgEquipmentQuery) FirstIDX(ctx context.Context) int {
	id, err := ceq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CfgEquipment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CfgEquipment entity is found.
// Returns a *NotFoundError when no CfgEquipment entities are found.
func (ceq *CfgEquipmentQuery) Only(ctx context.Context) (*CfgEquipment, error) {
	nodes, err := ceq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cfgequipment.Label}
	default:
		return nil, &NotSingularError{cfgequipment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ceq *CfgEquipmentQuery) OnlyX(ctx context.Context) *CfgEquipment {
	node, err := ceq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CfgEquipment ID in the query.
// Returns a *NotSingularError when more than one CfgEquipment ID is found.
// Returns a *NotFoundError when no entities are found.
func (ceq *CfgEquipmentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ceq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cfgequipment.Label}
	default:
		err = &NotSingularError{cfgequipment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ceq *CfgEquipmentQuery) OnlyIDX(ctx context.Context) int {
	id, err := ceq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CfgEquipments.
func (ceq *CfgEquipmentQuery) All(ctx context.Context) ([]*CfgEquipment, error) {
	if err := ceq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ceq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ceq *CfgEquipmentQuery) AllX(ctx context.Context) []*CfgEquipment {
	nodes, err := ceq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CfgEquipment IDs.
func (ceq *CfgEquipmentQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ceq.Select(cfgequipment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ceq *CfgEquipmentQuery) IDsX(ctx context.Context) []int {
	ids, err := ceq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ceq *CfgEquipmentQuery) Count(ctx context.Context) (int, error) {
	if err := ceq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ceq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ceq *CfgEquipmentQuery) CountX(ctx context.Context) int {
	count, err := ceq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ceq *CfgEquipmentQuery) Exist(ctx context.Context) (bool, error) {
	if err := ceq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ceq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ceq *CfgEquipmentQuery) ExistX(ctx context.Context) bool {
	exist, err := ceq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CfgEquipmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ceq *CfgEquipmentQuery) Clone() *CfgEquipmentQuery {
	if ceq == nil {
		return nil
	}
	return &CfgEquipmentQuery{
		config:     ceq.config,
		limit:      ceq.limit,
		offset:     ceq.offset,
		order:      append([]OrderFunc{}, ceq.order...),
		predicates: append([]predicate.CfgEquipment{}, ceq.predicates...),
		// clone intermediate query.
		sql:    ceq.sql.Clone(),
		path:   ceq.path,
		unique: ceq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Equipid int `json:"equipid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CfgEquipment.Query().
//		GroupBy(cfgequipment.FieldEquipid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ceq *CfgEquipmentQuery) GroupBy(field string, fields ...string) *CfgEquipmentGroupBy {
	grbuild := &CfgEquipmentGroupBy{config: ceq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ceq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ceq.sqlQuery(ctx), nil
	}
	grbuild.label = cfgequipment.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Equipid int `json:"equipid,omitempty"`
//	}
//
//	client.CfgEquipment.Query().
//		Select(cfgequipment.FieldEquipid).
//		Scan(ctx, &v)
//
func (ceq *CfgEquipmentQuery) Select(fields ...string) *CfgEquipmentSelect {
	ceq.fields = append(ceq.fields, fields...)
	selbuild := &CfgEquipmentSelect{CfgEquipmentQuery: ceq}
	selbuild.label = cfgequipment.Label
	selbuild.flds, selbuild.scan = &ceq.fields, selbuild.Scan
	return selbuild
}

func (ceq *CfgEquipmentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ceq.fields {
		if !cfgequipment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ceq.path != nil {
		prev, err := ceq.path(ctx)
		if err != nil {
			return err
		}
		ceq.sql = prev
	}
	return nil
}

func (ceq *CfgEquipmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CfgEquipment, error) {
	var (
		nodes = []*CfgEquipment{}
		_spec = ceq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CfgEquipment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CfgEquipment{config: ceq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ceq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ceq *CfgEquipmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ceq.querySpec()
	_spec.Node.Columns = ceq.fields
	if len(ceq.fields) > 0 {
		_spec.Unique = ceq.unique != nil && *ceq.unique
	}
	return sqlgraph.CountNodes(ctx, ceq.driver, _spec)
}

func (ceq *CfgEquipmentQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := ceq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (ceq *CfgEquipmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   cfgequipment.Table,
			Columns: cfgequipment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cfgequipment.FieldID,
			},
		},
		From:   ceq.sql,
		Unique: true,
	}
	if unique := ceq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ceq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cfgequipment.FieldID)
		for i := range fields {
			if fields[i] != cfgequipment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ceq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ceq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ceq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ceq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ceq *CfgEquipmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ceq.driver.Dialect())
	t1 := builder.Table(cfgequipment.Table)
	columns := ceq.fields
	if len(columns) == 0 {
		columns = cfgequipment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ceq.sql != nil {
		selector = ceq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ceq.unique != nil && *ceq.unique {
		selector.Distinct()
	}
	for _, p := range ceq.predicates {
		p(selector)
	}
	for _, p := range ceq.order {
		p(selector)
	}
	if offset := ceq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ceq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CfgEquipmentGroupBy is the group-by builder for CfgEquipment entities.
type CfgEquipmentGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cegb *CfgEquipmentGroupBy) Aggregate(fns ...AggregateFunc) *CfgEquipmentGroupBy {
	cegb.fns = append(cegb.fns, fns...)
	return cegb
}

// Scan applies the group-by query and scans the result into the given value.
func (cegb *CfgEquipmentGroupBy) Scan(ctx context.Context, v any) error {
	query, err := cegb.path(ctx)
	if err != nil {
		return err
	}
	cegb.sql = query
	return cegb.sqlScan(ctx, v)
}

func (cegb *CfgEquipmentGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range cegb.fields {
		if !cfgequipment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cegb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cegb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cegb *CfgEquipmentGroupBy) sqlQuery() *sql.Selector {
	selector := cegb.sql.Select()
	aggregation := make([]string, 0, len(cegb.fns))
	for _, fn := range cegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cegb.fields)+len(cegb.fns))
		for _, f := range cegb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cegb.fields...)...)
}

// CfgEquipmentSelect is the builder for selecting fields of CfgEquipment entities.
type CfgEquipmentSelect struct {
	*CfgEquipmentQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ces *CfgEquipmentSelect) Scan(ctx context.Context, v any) error {
	if err := ces.prepareQuery(ctx); err != nil {
		return err
	}
	ces.sql = ces.CfgEquipmentQuery.sqlQuery(ctx)
	return ces.sqlScan(ctx, v)
}

func (ces *CfgEquipmentSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := ces.sql.Query()
	if err := ces.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
