// Code generated by ent, DO NOT EDIT.

package ent

import (
	"harvest/app/worker/internal/data/ent/cfgequipment"
	"harvest/app/worker/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cfgequipmentFields := schema.CfgEquipment{}.Fields()
	_ = cfgequipmentFields
	// cfgequipmentDescEventlocked is the schema descriptor for eventlocked field.
	cfgequipmentDescEventlocked := cfgequipmentFields[6].Descriptor()
	// cfgequipment.DefaultEventlocked holds the default value on creation for the eventlocked field.
	cfgequipment.DefaultEventlocked = cfgequipmentDescEventlocked.Default.(int)
	// cfgequipmentDescControllocked is the schema descriptor for controllocked field.
	cfgequipmentDescControllocked := cfgequipmentFields[7].Descriptor()
	// cfgequipment.DefaultControllocked holds the default value on creation for the controllocked field.
	cfgequipment.DefaultControllocked = cfgequipmentDescControllocked.Default.(int)
	// cfgequipmentDescEquipaddress is the schema descriptor for equipaddress field.
	cfgequipmentDescEquipaddress := cfgequipmentFields[18].Descriptor()
	// cfgequipment.DefaultEquipaddress holds the default value on creation for the equipaddress field.
	cfgequipment.DefaultEquipaddress = cfgequipmentDescEquipaddress.Default.(int)
}
