// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CfgequipmentColumns holds the columns for the "cfgequipment" table.
	CfgequipmentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "equipid", Type: field.TypeInt, Unique: true},
		{Name: "portid", Type: field.TypeInt},
		{Name: "monitorunitid", Type: field.TypeInt},
		{Name: "equiptemplateid", Type: field.TypeInt},
		{Name: "equipname", Type: field.TypeString},
		{Name: "exportsetting", Type: field.TypeString, Nullable: true},
		{Name: "eventlocked", Type: field.TypeInt, Default: 0},
		{Name: "controllocked", Type: field.TypeInt, Default: 0},
		{Name: "extendfield1", Type: field.TypeString, Nullable: true},
		{Name: "extendfield2", Type: field.TypeString, Nullable: true},
		{Name: "extendfield3", Type: field.TypeString, Nullable: true},
		{Name: "extendfield4", Type: field.TypeString, Nullable: true},
		{Name: "extendfield5", Type: field.TypeString, Nullable: true},
		{Name: "roomid", Type: field.TypeInt},
		{Name: "equiptype", Type: field.TypeInt},
		{Name: "sampleinterval", Type: field.TypeInt},
		{Name: "libname", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "equipaddress", Type: field.TypeInt, Default: 1},
	}
	// CfgequipmentTable holds the schema information for the "cfgequipment" table.
	CfgequipmentTable = &schema.Table{
		Name:       "cfgequipment",
		Columns:    CfgequipmentColumns,
		PrimaryKey: []*schema.Column{CfgequipmentColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CfgequipmentTable,
	}
)

func init() {
	CfgequipmentTable.Annotation = &entsql.Annotation{
		Table: "cfgequipment",
	}
}
