// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.1
// - protoc             v3.17.3
// source: api/equipment/v1/equipment.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEquipmentGetEquipment = "/equipment.v1.Equipment/GetEquipment"

type EquipmentHTTPServer interface {
	GetEquipment(context.Context, *GetEquipmentRequest) (*GetEquipmentReply, error)
}

func RegisterEquipmentHTTPServer(s *http.Server, srv EquipmentHTTPServer) {
	r := s.Route("/")
	r.GET("/equipment/{equip_id}", _Equipment_GetEquipment0_HTTP_Handler(srv))
}

func _Equipment_GetEquipment0_HTTP_Handler(srv EquipmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEquipmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEquipmentGetEquipment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEquipment(ctx, req.(*GetEquipmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEquipmentReply)
		return ctx.Result(200, reply)
	}
}

type EquipmentHTTPClient interface {
	GetEquipment(ctx context.Context, req *GetEquipmentRequest, opts ...http.CallOption) (rsp *GetEquipmentReply, err error)
}

type EquipmentHTTPClientImpl struct {
	cc *http.Client
}

func NewEquipmentHTTPClient(client *http.Client) EquipmentHTTPClient {
	return &EquipmentHTTPClientImpl{client}
}

func (c *EquipmentHTTPClientImpl) GetEquipment(ctx context.Context, in *GetEquipmentRequest, opts ...http.CallOption) (*GetEquipmentReply, error) {
	var out GetEquipmentReply
	pattern := "/equipment/{equip_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEquipmentGetEquipment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
