// Code generated by ent, DO NOT EDIT.

package cfgequipment

const (
	// Label holds the string label denoting the cfgequipment type in the database.
	Label = "cfg_equipment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEquipid holds the string denoting the equipid field in the database.
	FieldEquipid = "equipid"
	// FieldPortid holds the string denoting the portid field in the database.
	FieldPortid = "portid"
	// FieldMonitorunitid holds the string denoting the monitorunitid field in the database.
	FieldMonitorunitid = "monitorunitid"
	// FieldEquiptemplateid holds the string denoting the equiptemplateid field in the database.
	FieldEquiptemplateid = "equiptemplateid"
	// FieldEquipname holds the string denoting the equipname field in the database.
	FieldEquipname = "equipname"
	// FieldExportsetting holds the string denoting the exportsetting field in the database.
	FieldExportsetting = "exportsetting"
	// FieldEventlocked holds the string denoting the eventlocked field in the database.
	FieldEventlocked = "eventlocked"
	// FieldControllocked holds the string denoting the controllocked field in the database.
	FieldControllocked = "controllocked"
	// FieldExtendfield1 holds the string denoting the extendfield1 field in the database.
	FieldExtendfield1 = "extendfield1"
	// FieldExtendfield2 holds the string denoting the extendfield2 field in the database.
	FieldExtendfield2 = "extendfield2"
	// FieldExtendfield3 holds the string denoting the extendfield3 field in the database.
	FieldExtendfield3 = "extendfield3"
	// FieldExtendfield4 holds the string denoting the extendfield4 field in the database.
	FieldExtendfield4 = "extendfield4"
	// FieldExtendfield5 holds the string denoting the extendfield5 field in the database.
	FieldExtendfield5 = "extendfield5"
	// FieldRoomid holds the string denoting the roomid field in the database.
	FieldRoomid = "roomid"
	// FieldEquiptype holds the string denoting the equiptype field in the database.
	FieldEquiptype = "equiptype"
	// FieldSampleinterval holds the string denoting the sampleinterval field in the database.
	FieldSampleinterval = "sampleinterval"
	// FieldLibname holds the string denoting the libname field in the database.
	FieldLibname = "libname"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEquipaddress holds the string denoting the equipaddress field in the database.
	FieldEquipaddress = "equipaddress"
	// Table holds the table name of the cfgequipment in the database.
	Table = "cfgequipment"
)

// Columns holds all SQL columns for cfgequipment fields.
var Columns = []string{
	FieldID,
	FieldEquipid,
	FieldPortid,
	FieldMonitorunitid,
	FieldEquiptemplateid,
	FieldEquipname,
	FieldExportsetting,
	FieldEventlocked,
	FieldControllocked,
	FieldExtendfield1,
	FieldExtendfield2,
	FieldExtendfield3,
	FieldExtendfield4,
	FieldExtendfield5,
	FieldRoomid,
	FieldEquiptype,
	FieldSampleinterval,
	FieldLibname,
	FieldDescription,
	FieldEquipaddress,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEventlocked holds the default value on creation for the "eventlocked" field.
	DefaultEventlocked int
	// DefaultControllocked holds the default value on creation for the "controllocked" field.
	DefaultControllocked int
	// DefaultEquipaddress holds the default value on creation for the "equipaddress" field.
	DefaultEquipaddress int
)
